categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "📝 Documentation"
    labels:
      - "documentation"
  - title: "⚠️ Duplicates"
    labels:
      - "duplicate"
  - title: "👶 First Issues"
    labels:
      - "good first issue"
  - title: "🛠 Help Wanted"
    labels:
      - "help wanted"
  - title: "❌ Invalid"
    labels:
      - "invalid"
  - title: "❓ Questions"
    labels:
      - "question"
  - title: "🚫 Won't Fix"
    labels:
      - "wontfix"

template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

  ## Pull Requests
  $PULL_REQUESTS
