name-template: 'Release ${{ tag_name }}'
tag-template: 'v${{ version }}'
categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧹 Chores"
    labels:
      - "chore"
template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
change-template: '- ${{ title }} (#${{ number }}) by @${{ author }}'
