name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
      branch:
        description: "Branch to release from"
        required: true
        default: "main"

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: ${{ github.event.inputs.branch }}
          tag-prefix: v
          output-file: CHANGELOG.md

      # Get Closed and Merged PR Details
      - name: Get Closed and Merged PR
        id: get_pr
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          filterOutClosed: false
          filterOutDraft: true

      # Debug PR Details
      - name: Debug PR Details
        run: |
          echo "PR Found: ${{ steps.get_pr.outputs.pr_found }}"
          echo "PR Number: ${{ steps.get_pr.outputs.number }}"
          echo "PR Title: ${{ steps.get_pr.outputs.pr_title }}"
          echo "PR User: ${{ steps.get_pr.outputs.pr_user_login }}"

      # Append PR Details to Changelog
      - name: Append PR Details to Changelog
        if: steps.get_pr.outputs.pr_found == 'true'
        run: |
          echo "### Merged Pull Requests" >> CHANGELOG.md
          echo "- PR Number: ${{ steps.get_pr.outputs.number }}" >> CHANGELOG.md
          echo "- PR Branch: ${{ github.event.inputs.branch }}" >> CHANGELOG.md
          echo "- PR Title: ${{ steps.get_pr.outputs.pr_title || 'Title not available' }}" >> CHANGELOG.md
          echo "- PR Author: ${{ steps.get_pr.outputs.pr_user_login || 'Author not available' }}" >> CHANGELOG.md

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
