name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: QM-508

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: QM-508
          tag-prefix: v
          output-file: CHANGELOG.md

      # List Closed PRs with Details based on label
      - name: List Closed Pull Requests
        id: list_prs
        uses: buildsville/list-pull-requests@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'closed'
          labels: '["WFR"]' # Example label filter

      # Debug the PRs Retrieved
      - name: Debug PRs Retrieved
        run: echo "PRs Retrieved:${{ steps.list_prs.outputs.pull_requests }}"

      # Append PR Details to Changelog
      - name: Append PR Details to Changelog
        run: |
          echo "Release ${{ env.NEW_TAG }} Latest" >> CHANGELOG.md
          echo "### PR Details" >> CHANGELOG.md
          echo "${{ steps.list_prs.outputs.pull_requests }}" | jq -r '.[] | "- PR [#\(.number)](\(.url)): \(.title) by @\(.user.login)"' >> CHANGELOG.md

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
