name: Tag and Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Fetch Merged PRs
        id: pr_details
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              base: 'main', // Change this to your default branch if it's not 'main'
              per_page: 100
            });
            const mergedPrs = prs.data.filter(pr => pr.merged_at !== null);
            return mergedPrs.map(pr => `PR #${pr.number}: ${pr.title} by @${pr.user.login}`).join('\n');

      - name: Log PR Details
        run: echo "Merged PRs:${{ steps.pr_details.outputs.result }}"

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: ${{ github.ref_name }}
          tag-prefix: v
          output-file: CHANGELOG.md

      - name: Append Merged PRs to Changelog
        run: |
          echo "\n### Merged PRs" >> CHANGELOG.md
          echo "${{ steps.pr_details.outputs.result }}" >> CHANGELOG.md

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body: "${{ steps.changelog.outputs.changelog }}"
          draft: false
          prerelease: false
