name: Create Release with PR Details

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fetch closed PR details
      - name: Generate release notes
        id: release_notes
        uses: repo-sync/github-sync-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-prs: true
          filter: closed # Include closed PRs

      # Create a release
      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
