name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history to tag correctly
          ref: pr-branch  # Specify the branch to check out (replace `pr-branch` with your branch name)

      # Get Closed and Merged PR Details
      - name: Get Closed and Merged PR
        id: get_pr
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token to authenticate
          filterOutClosed: false  # Include closed PRs (merged PRs will also be included)
          filterOutDraft: true  # Exclude draft PRs

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: pr-branch
          tag-prefix: v
          output-file: CHANGELOG.md

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Show PR details (for merged PR)
      - name: Show PR Details
        if: steps.get_pr.outputs.pr_found == 'true'
        run: |
          echo "PR Number: ${{ steps.get_pr.outputs.number }}"
          echo "PR Title: ${{ steps.get_pr.outputs.pr_title }}"
          echo "PR URL: ${{ steps.get_pr.outputs.pr_url }}"
          echo "PR Body: ${{ steps.get_pr.outputs.pr_body }}"
          echo "PR Created At: ${{ steps.get_pr.outputs.pr_created_at }}"
          echo "PR Merged At: ${{ steps.get_pr.outputs.pr_merged_at }}"
          echo "PR Closed At: ${{ steps.get_pr.outputs.pr_closed_at }}"
          echo "PR Labels: ${{ steps.get_pr.outputs.pr_labels }}"
