name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Merged PR Information
        id: get_pr
        uses: coin-tracker/get-merged-pull-request-information@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Append Merged PR Details to Changelog
        run: |
          echo "### Merged Pull Requests" >> CHANGELOG.md
          echo "- PR [#${{ steps.get_pr.outputs.number }}](${{ steps.get_pr.outputs.html_url }}): ${{ steps.get_pr.outputs.title }} by @${{ steps.get_pr.outputs.assignees }}" >> CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            $(cat CHANGELOG.md)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
