name: Create Release

on:
  push:
    branches:
      - release # Trigger on pushes to the 'release' branch

jobs:
  build:
    runs-on: ubuntu-latest # Choose your desired runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        uses: softprops/action-gh-release@v6
        with:
          draft: false # Set to true for draft releases
          prerelease: false # Set to true for pre-release
          tag_name: ${{ github.ref_name }} # Use the release branch name as tag
          name: ${{ github.ref_name }} # Use the release name
          body: |
            *Release Notes:*
             *Merged from:** ${{ github.event.pull_request.html_url }} 
             *Title:** ${{ github.event.pull_request.title }}
             *Author:** ${{ github.event.pull_request.user.login }}
             *Description:** ${{ github.event.pull_request.body }}
