name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
      pr_number:
        description: "Pull Request Number"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Fetch PR details using GitHub Script
      - name: Fetch PR Details
        id: fetch_pr_details
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ github.event.inputs.pr_number }};
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            return {
              title: pr.title,
              body: pr.body,
              number: pr.number
            };

      # Output the fetched PR details to debug
      - name: Debug PR Details
        run: |
          echo "PR Title: ${{ steps.fetch_pr_details.outputs.title }}"
          echo "PR Body: ${{ steps.fetch_pr_details.outputs.body }}"
          echo "PR Number: ${{ steps.fetch_pr_details.outputs.number }}"

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: pr-branch
          tag-prefix: v
          output-file: CHANGELOG.md

      # Add PR details to Changelog
      - name: Add PR Details to Changelog
        run: |
          echo "PR Title: ${{ steps.fetch_pr_details.outputs.title }}" >> CHANGELOG.md
          echo "PR Body: ${{ steps.fetch_pr_details.outputs.body }}" >> CHANGELOG.md
          echo "PR Number: ${{ steps.fetch_pr_details.outputs.number }}" >> CHANGELOG.md

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
