name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: pr-branch

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: pr-branch
          tag-prefix: v
          output-file: CHANGELOG.md

      # Get PR Details using Get PR Action
      - name: Get PR Details
        uses: cloudposse-github-actions/get-pr@main
        id: pr_details
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.number }}

      # Extract PR Author from the PR Details output
      - name: Extract PR Author
        id: extract_author
        run: |
          PR_AUTHOR="${{ fromJSON(steps.pr_details.outputs.json).user.login }}"
          echo "PR_AUTHOR=${PR_AUTHOR}" >> $GITHUB_ENV

      # Fetch Closed PRs
      - name: Fetch Closed PRs
        id: fetch_closed_prs
        run: |
          CLOSED_PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed")
          echo "CLOSED_PRS=${CLOSED_PRS}" >> $GITHUB_ENV

      # Append Closed PR Details to Changelog
      - name: Append Closed PR Details to Changelog
        run: |
          echo "### Closed PRs" >> CHANGELOG.md
          for pr in $(echo "${{ env.CLOSED_PRS }}" | jq -c '.[]'); do
            PR_NUMBER=$(echo "$pr" | jq -r '.number')
            PR_TITLE=$(echo "$pr" | jq -r '.title')
            PR_URL=$(echo "$pr" | jq -r '.html_url')
            PR_AUTHOR=$(echo "$pr" | jq -r '.user.login')
            echo "- PR [#$PR_NUMBER]($PR_URL): $PR_TITLE by @$PR_AUTHOR" >> CHANGELOG.md
          done

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
