name: Tag, Release, and Fetch Merged PR Details

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (ensure the branch is dynamically determined or set correctly)
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}  # Automatically picks the branch from the context

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: ${{ github.ref }}
          tag-prefix: v
          output-file: CHANGELOG.md

      # Fetch Merged Pull Request Details (Place this before the release step)
      - name: Fetch Merged PR Details
        uses: coin-tracker/get-merged-pull-request@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Append Merged PR Details to Changelog
        run: |
          echo "## Merged PRs" >> CHANGELOG.md
          echo "### PR Title: ${{ steps.get-merged-pr-info.outputs.title }}" >> CHANGELOG.md
          echo "PR Number: ${{ steps.get-merged-pr-info.outputs.number }}" >> CHANGELOG.md
          echo "PR Labels: ${{ steps.get-merged-pr-info.outputs.labels }}" >> CHANGELOG.md
          echo "PR Assignees: ${{ steps.get-merged-pr-info.outputs.assignees }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md  # Adds a new line to separate PRs

      # Create GitHub Release (This is now the last step)
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
