name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: QM-508

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: QM-508
          tag-prefix: v
          output-file: CHANGELOG.md

      # Get Merged PR Details
      - name: Get Merged PR Details
        uses: some-action-to-get-merged-pr-details

      # Get Current PR Details using Get PR Action
      - name: Get Current PR Details
        uses: cloudposse-github-actions/get-pr@main
        id: pr_details
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.number }}

      # Extract PR Author from the PR Details output
      - name: Extract PR Author
        id: extract_author
        run: |
          PR_AUTHOR="${{ fromJSON(steps.pr_details.outputs.json).user.login }}"
          echo "PR_AUTHOR=${PR_AUTHOR}" >> $GITHUB_ENV

      # Append PR Details to the Changelog
      - name: Append PR Details to Changelog
        run: |
          PR_NUMBER="${{ fromJSON(steps.pr_details.outputs.json).number }}"
          PR_TITLE="${{ fromJSON(steps.pr_details.outputs.json).title }}"
          PR_URL="${{ fromJSON(steps.pr_details.outputs.json).url }}"
          PR_AUTHOR="${{ env.PR_AUTHOR }}"
          
          echo "### Merged PR Details" >> CHANGELOG.md
          echo "- Details of merged PRs go here" >> CHANGELOG.md
          
          echo "### Current PR Details" >> CHANGELOG.md
          echo "- PR [#$PR_NUMBER]($PR_URL): $PR_TITLE by @$PR_AUTHOR" >> CHANGELOG.md

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
