name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: pr-branch

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: pr-branch
          tag-prefix: v
          output-file: CHANGELOG.md

      # Fetch merged pull request details
      - name: Get Merged Pull Request Details
        id: get-merged-pr
        uses: benlei/find-merged-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Extract details from the action output and set them as environment variables
      - name: Set PR Details as Environment Variables
        run: |
          echo "PR_NUMBER=${{ steps.get-merged-pr.outputs.number }}" >> $GITHUB_ENV
          echo "PR_TITLE=${{ steps.get-merged-pr.outputs.title }}" >> $GITHUB_ENV
          echo "PR_BODY=${{ steps.get-merged-pr.outputs.body }}" >> $GITHUB_ENV

      # Debug Output to see PR details
      - name: Debug Merged PR Details
        run: |
          echo "PR Number: ${{ env.PR_NUMBER }}"
          echo "PR Title: ${{ env.PR_TITLE }}"
          echo "PR Body: ${{ env.PR_BODY }}"

      # Append Merged PR Details to Changelog
      - name: Append Merged PR Details to Changelog
        run: |
          echo -e "\n## Merged Pull Request Details:" >> CHANGELOG.md
          echo "Number: ${{ env.PR_NUMBER }}" >> CHANGELOG.md
          echo "Title: ${{ env.PR_TITLE }}" >> CHANGELOG.md
          echo "Body: ${{ env.PR_BODY }}" >> CHANGELOG.md

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
