name: Tag and Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
         

      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Get Current PR
        id: PR
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log PR Details
        if: steps.PR.outputs.pr_found == 'true'
        run: |
          echo "PR Number: ${{ steps.PR.outputs.number }}"
          echo "PR Title: ${{ steps.PR.outputs.pr_title }}"
          echo "PR URL: ${{ steps.PR.outputs.pr_url }}"
          echo "PR Merged At: ${{ steps.PR.outputs.pr_merged_at }}"
        env:
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}

      - name: Check If PR is Merged
        if: steps.PR.outputs.pr_found == 'true' && steps.PR.outputs.pr_merged_at != ''
        run: echo "This PR is merged!"

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: ${{ github.ref_name }}
          tag-prefix: v
          output-file: CHANGELOG.md
     
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body: "${{ steps.changelog.outputs.changelog }}"
          draft: false
          prerelease: false
