name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: pr-branch
          tag-prefix: v
          output-file: CHANGELOG.md

      - name: Truncate Changelog
        run: |
          original_length=$(wc -c < CHANGELOG.md)
          head -c 124900 CHANGELOG.md > TRUNCATED_CHANGELOG.md
          truncated_length=$(wc -c < TRUNCATED_CHANGELOG.md)
          echo "\n...Truncated due to length limitations. (Original length: $original_length characters, Truncated length: $truncated_length characters)" >> TRUNCATED_CHANGELOG.md

      # Fetch Merged PRs using GitHub API
      - name: Fetch Merged PRs
        uses: octokit/request-action@v2.4.0
        id: fetch_merged_prs
        with:
          route: GET /repos/{owner}/{repo}/pulls
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          state: closed
          base: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Append Merged PR Details to Changelog
      - name: Append Merged PR Details to Changelog
        run: |
          echo "### Merged PRs" >> TRUNCATED_CHANGELOG.md
          echo "${{ steps.fetch_merged_prs.outputs.data }}" >> TRUNCATED_CHANGELOG.md

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: TRUNCATED_CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
