name: Tag and release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          git-branch: pr-branch

      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: pr-branch
          tag-prefix: v
          output-file: CHANGELOG.md

      - name: List All Closed Pull Requests in Last 24 Hours
        id: list_prs
        uses: andrea-armstrong/github-list-pull-requests@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: 'closed'
          window: '24'

      - name: Fetch Pull Request Details
        id: fetch_pr_details
        uses: marten-denneboom/closed-pr-details@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-numbers: ${{ steps.list_prs.outputs.pullRequestNumbers }}

      - name: Output Closed Pull Requests
        run: echo "Closed PR Details: ${{ steps.fetch_pr_details.outputs.details }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body: "${{ steps.changelog.outputs.changelog }}\nClosed PR Details: ${{ steps.fetch_pr_details.outputs.details }}"
          draft: false
          prerelease: false
