name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: pr-branch

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Fetch PR Details using Octokit
      - name: Fetch PR Details using Octokit
        id: fetch_pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Debugging the output of Fetch PR Details
      - name: Debug PR Output
        run: |
          echo "Raw PR Details Output: ${{ steps.fetch_pr.outputs.data }}"

      # Debug PR Details - Check if fields are correctly parsed
      - name: Debug PR Details
        run: |
          PR_NUMBER="${{ fromJson(steps.fetch_pr.outputs.data).number }}"
          PR_BRANCH="${{ fromJson(steps.fetch_pr.outputs.data).head.ref }}"
          PR_TITLE="${{ fromJson(steps.fetch_pr.outputs.data).title }}"
          PR_AUTHOR="${{ fromJson(steps.fetch_pr.outputs.data).user.login }}"
          
          # Print values to verify parsing
          echo "PR Number: $PR_NUMBER"
          echo "PR Branch: $PR_BRANCH"
          echo "PR Title: $PR_TITLE"
          echo "PR Author: $PR_AUTHOR"

      # Append PR Details to Changelog
      - name: Append PR Details to Changelog
        run: |
          # Fetch PR details from previous step
          PR_NUMBER="${{ fromJson(steps.fetch_pr.outputs.data).number }}"
          PR_BRANCH="${{ fromJson(steps.fetch_pr.outputs.data).head.ref }}"
          PR_TITLE="${{ fromJson(steps.fetch_pr.outputs.data).title }}"
          PR_AUTHOR="${{ fromJson(steps.fetch_pr.outputs.data).user.login }}"
          
          # Create Changelog with Release Version and PR Details
          echo "Release ${{ env.NEW_TAG }} Latest" >> CHANGELOG.md
          echo "### PR Details" >> CHANGELOG.md
          echo "PR #$PR_NUMBER: [$PR_BRANCH] - $PR_TITLE by @$PR_AUTHOR" >> CHANGELOG.md
     
      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
