name: Auto Release and PR Info

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch PR Information
        id: pr_info
        run: |
          pr_number=${{ github.event.pull_request.number }}
          pr_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                     "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number")
          echo "::set-output name=title::$(echo $pr_info | jq -r .title)"
          echo "::set-output name=author::$(echo $pr_info | jq -r .user.login)"
          echo "::set-output name=number::$(echo $pr_info | jq -r .number)"
          echo "::set-output name=body::$(echo $pr_info | jq -r .body)"

      - name: Debug PR Info
        run: |
          echo "Title: ${{ steps.pr_info.outputs.title }}"
          echo "Author: ${{ steps.pr_info.outputs.author }}"
          echo "Number: ${{ steps.pr_info.outputs.number }}"
          echo "Description: ${{ steps.pr_info.outputs.body }}"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.pr_info.outputs.number }}
          release_name: Release ${{ steps.pr_info.outputs.number }}
          body: |
            **Title:** ${{ steps.pr_info.outputs.title }}
            **Author:** ${{ steps.pr_info.outputs.author }}
            **PR Number:** ${{ steps.pr_info.outputs.number }}
            **PR Description:** ${{ steps.pr_info.outputs.body }}
          draft: false
          prerelease: false
