name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: pr-branch

      # Tag and Release
      - name: Tag and Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.release_type }}
          tag_prefix: v

      # Export the new tag
      - name: Get New Tag
        run: echo "NEW_TAG=${{ steps.tag_release.outputs.new_tag }}" >> $GITHUB_ENV

      # Generate Changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: pr-branch
          tag-prefix: v
          output-file: CHANGELOG.md

      # Get merged PR details
      - name: Get Merged PR Details
        uses: yu-iskw/merged-pr-info-action@v1.0.1
        id: merged-pr-info
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Output Merged PR Details (Optional)
      - name: Display Merged PR Details
        run: |
          echo "PR Number: ${{ steps.merged-pr-info.outputs.pull-request-number }}"
          echo "PR Title: ${{ steps.merged-pr-info.outputs.pull-request-title }}"
          echo "PR Creator: ${{ steps.merged-pr-info.outputs.pull-request-creator }}"
          echo "PR Body: ${{ steps.merged-pr-info.outputs.pull-request-body }}"
          echo "PR URL: ${{ steps.merged-pr-info.outputs.pull-request-url }}

           # Check if PR Number is available
          if [ -z "$PR_NUMBER" ]; then
            echo "Error: PR details not found."
            exit 1
          fi
          
          # Append PR details to the changelog
          echo "Release ${{ env.NEW_TAG }} Latest" >> CHANGELOG.md
          echo "### PR Details" >> CHANGELOG.md
          echo "- PR [#$PR_NUMBER]($PR_URL): $PR_TITLE by @$PR_AUTHOR" >> CHANGELOG.md

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.NEW_TAG }}"
          release_name: "Release ${{ env.NEW_TAG }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
