name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js (optional, depending on your project)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR Information
        id: pr_info
        run: |
          PRS=$(gh pr list --state merged --base main --json number,title,url --jq '.[] | "PR #\(.number): \(.title) - \(.url)"')
          echo "PRS=$PRS" >> $GITHUB_ENV

      - name: Add PR Info to Release Notes
        run: |
          echo "Release Notes: ${{ env.PRS }}" >> $GITHUB_ENV

      - name: Publish Release with PR Info
        run: |
          gh release create ${{ github.sha }} --title "Release ${{ github.sha }}" --notes "${{ env.PRS }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
